name: Generate snake animation

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/12 * * *'
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-metrics.svg

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.0
        with:
          build_dir: dist/
          target_branch: output 
